Задание 1.Создайте numpy array с элементами от числа N до 0 
(например, для N = 10 это будет array ([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [26]:
import numpy as np
n = 10
A = np.arange(n)[::-1]
A

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

Задание 2.Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [33]:
n = 10
A = np.arange(n)
A = np.flip(A)
A = np.diag(A)
s = np.sum(A)
print(A)
print('Сумма значений на диагонали:', s)

[[9 0 0 0 0 0 0 0 0 0]
 [0 8 0 0 0 0 0 0 0 0]
 [0 0 7 0 0 0 0 0 0 0]
 [0 0 0 6 0 0 0 0 0 0]
 [0 0 0 0 5 0 0 0 0 0]
 [0 0 0 0 0 4 0 0 0 0]
 [0 0 0 0 0 0 3 0 0 0]
 [0 0 0 0 0 0 0 2 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0]]
Сумма значений на диагонали: 45


Задание 3. Решите систему уравнений:

4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3

In [37]:
from numpy import linalg
a = np.array([[4,2,1],[1,3,0],[0,5,4]])
b = np.array([4,12,-3])
linalg.solve(a,b)

array([ 0.46666667,  3.84444444, -5.55555556])